### ISSUE TITLE
Upgrade doesn't work if wrong value in configmap (2.8.0-> 2.9.0)

### ISSUE THREAD

**Issue by saurabhwani5** [IBM/ibm-spectrum-scale-csi#952]
## Describe the bug
Whenever we create new configmap and add wrong value in it for float no then upgrade fails with the following error

## How to Reproduce?

1. Install CSI 2.8.0 
```
root@deebugk8s1:~# kn get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.8.0     True
root@deebugk8s1:~# kn get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-42qd7                          3/3     Running   0          17s
ibm-spectrum-scale-csi-4rn8z                          3/3     Running   0          17s
ibm-spectrum-scale-csi-92545                          3/3     Running   0          17s
ibm-spectrum-scale-csi-9hr6j                          3/3     Running   0          17s
ibm-spectrum-scale-csi-9kt9j                          3/3     Running   0          17s
ibm-spectrum-scale-csi-attacher-6df84d85c9-djpnk      1/1     Running   0          17s
ibm-spectrum-scale-csi-attacher-6df84d85c9-tkj8n      1/1     Running   0          17s
ibm-spectrum-scale-csi-bj6rz                          3/3     Running   0          17s
ibm-spectrum-scale-csi-d6nkj                          3/3     Running   0          17s
ibm-spectrum-scale-csi-ftk9w                          3/3     Running   0          17s
ibm-spectrum-scale-csi-hntmv                          3/3     Running   0          17s
ibm-spectrum-scale-csi-hrk5q                          3/3     Running   0          17s
ibm-spectrum-scale-csi-k5tjv                          3/3     Running   0          17s
ibm-spectrum-scale-csi-kq6d6                          3/3     Running   0          17s
ibm-spectrum-scale-csi-n2rfj                          3/3     Running   0          17s
ibm-spectrum-scale-csi-operator-68958ccdfc-84b67      1/1     Running   0          40s
ibm-spectrum-scale-csi-provisioner-59847b9966-twfcj   1/1     Running   0          17s
ibm-spectrum-scale-csi-resizer-64d5d8c98b-zh4js       1/1     Running   0          17s
ibm-spectrum-scale-csi-rsw9k                          3/3     Running   0          17s
ibm-spectrum-scale-csi-snapshotter-68d854b9c9-rq5ft   1/1     Running   0          17s
ibm-spectrum-scale-csi-sw5t7                          3/3     Running   0          17s
ibm-spectrum-scale-csi-test-pod                       1/1     Running   0          39h
ibm-spectrum-scale-csi-v4cc5                          3/3     Running   0          17s
ibm-spectrum-scale-csi-wkjlw                          3/3     Running   0          17s
ibm-spectrum-scale-csi-x5789                          3/3     Running   0          17s
ibm-spectrum-scale-csi-xchvb                          3/3     Running   0          17s
```
2. Create a configmap as following(without %) :
```
root@deebugk8s1:~/bnp# kn apply -f cm.yaml
configmap/ibm-spectrum-scale-csi-config configured
root@deebugk8s1:~/bnp# cat cm.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: ibm-spectrum-scale-csi-config
  namespace: ibm-spectrum-scale-csi-driver
data:
  DRIVER_UPGRADE_MaxUnavailable: "80"
```
3. Upgrade CSI to 2.9.0 : 
```
root@deebugk8s1:~/2.9.0/latest# kn apply -f ibm-spectrum-scale-csi-operator.yaml
deployment.apps/ibm-spectrum-scale-csi-operator configured
clusterrole.rbac.authorization.k8s.io/ibm-spectrum-scale-csi-operator configured
clusterrolebinding.rbac.authorization.k8s.io/ibm-spectrum-scale-csi-operator unchanged
serviceaccount/ibm-spectrum-scale-csi-operator unchanged
customresourcedefinition.apiextensions.k8s.io/csiscaleoperators.csi.ibm.com configured

```
4. Check if driver pods are recreating or not 
```
root@deebugk8s1:~/2.9.0/latest# kn get pods -w
NAME                                                  READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-42qd7                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-4rn8z                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-92545                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-9hr6j                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-9kt9j                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-attacher-85965f76cd-dj5kd      1/1     Running   0          61s
ibm-spectrum-scale-csi-attacher-85965f76cd-kttj7      1/1     Running   0          61s
ibm-spectrum-scale-csi-bj6rz                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-d6nkj                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-ftk9w                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-hntmv                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-hrk5q                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-k5tjv                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-kq6d6                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-n2rfj                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-operator-566f8fdf7f-zrj8h      1/1     Running   0          90s
ibm-spectrum-scale-csi-provisioner-b5db8c7d9-q486k    1/1     Running   0          61s
ibm-spectrum-scale-csi-resizer-686d8fffdd-6pl5w       1/1     Running   0          61s
ibm-spectrum-scale-csi-rsw9k                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-snapshotter-6bcf7b5d8b-r85lk   1/1     Running   0          61s
ibm-spectrum-scale-csi-sw5t7                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-test-pod                       1/1     Running   0          40h
ibm-spectrum-scale-csi-v4cc5                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-wkjlw                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-x5789                          3/3     Running   0          3m51s
ibm-spectrum-scale-csi-xchvb                          3/3     Running   0          3m51s
root@deebugk8s1:~# kn get cso  -w
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.8.0     True
ibm-spectrum-scale-csi   2.9.0     False
ibm-spectrum-scale-csi   2.9.0     False

CSO Description : 
  Warning  UpdateFailed  109s (x17 over 115s)  CSIScaleOperator  Synchronization of node/driver ibm-spectrum-scale-csi DaemonSet failed for the CSISCaleOperator instance ibm-spectrum-scale-csi
```

## Expected behaviour:
CSI should upgrade with predefined daemonset values if provided value by the user is false

**Comment by saurabhwani5** [comment]
Logs: scale-csi/D.952

**Comment by saurabhwani5** [comment]
Observation : this issue can be also recreated when configmap is already present and we direct install CSI 2.9.0 , pods will be as following : 
```
root@deebugk8s1:~# kn get pods
NAME                                                  READY   STATUS             RESTARTS   AGE
ibm-spectrum-scale-csi-attacher-85965f76cd-dfnlg      0/1     CrashLoopBackOff   4          112s
ibm-spectrum-scale-csi-attacher-85965f76cd-zmq6p      0/1     CrashLoopBackOff   4          112s
ibm-spectrum-scale-csi-operator-566f8fdf7f-4pf95      1/1     Running            0          2m21s
ibm-spectrum-scale-csi-provisioner-b5db8c7d9-74hf7    0/1     CrashLoopBackOff   4          112s
ibm-spectrum-scale-csi-resizer-686d8fffdd-s6zxh       0/1     CrashLoopBackOff   4          112s
ibm-spectrum-scale-csi-snapshotter-6bcf7b5d8b-9snhq   0/1     CrashLoopBackOff   4          112s
ibm-spectrum-scale-csi-test-pod                       1/1     Running            0          40h
root@deebugk8s1:~#
```

**Comment by badri-pathak** [comment]
Have addressed this issue in the same PR which is related to optional configMap variable validation.
https://github.com/IBM/ibm-spectrum-scale-csi/pull/947

**Comment by badri-pathak** [comment]
The fix will allow an upgrade from older to newer version even if there is an incorrect value of the MaxUnavailable variable. If  wrong value of the key is present in the configMap, the default value (which 1 Integer) being configured as upgradeStrategy.

**Comment by amdabhad** [comment]
This is fixed, please close if verified already

**Comment by saurabhwani5** [comment]
Hi @amdabhad , @badri-pathak , I see issue still there , I have tried upgrade from CSI 2.9.0 to CSI 2.10.0 (#1002 images), driver pods are still not getting upgraded with following error:
```
[root@saurabh6-master pr1002]# oc get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
ibm-spectrum-scale-csi-7p7bn                          3/3     Running   0          5m6s
ibm-spectrum-scale-csi-attacher-b6b6d4948-k6ttn       1/1     Running   0          52s
ibm-spectrum-scale-csi-attacher-b6b6d4948-klkvq       1/1     Running   0          52s
ibm-spectrum-scale-csi-operator-567f8455f5-98fhg      1/1     Running   0          75s
ibm-spectrum-scale-csi-provisioner-b456fbb49-l92ql    1/1     Running   0          52s
ibm-spectrum-scale-csi-resizer-84d84bfdf6-g5sm9       1/1     Running   0          52s
ibm-spectrum-scale-csi-snapshotter-656d4bd64f-5bvg5   1/1     Running   0          52s
ibm-spectrum-scale-csi-stpd8                          3/3     Running   0          5m6s
[root@saurabh6-master pr1002]# oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.10.0    False
Events:
  Type     Reason         Age                     From              Message
  ----     ------         ----                    ----              -------
  Warning  GUIConnFailed  6m20s (x13 over 7m16s)  CSIScaleOperator  Failed to connect to the GUI of the cluster with ID: 227604367530725699
  Normal   CSIConfigured  5m20s (x2 over 5m21s)   CSIScaleOperator  The CSI driver resources have been created/updated successfully
  Warning  UpdateFailed   4m25s (x2 over 5m21s)   CSIScaleOperator  Failed to set defaults on the instance ibm-spectrum-scale-csi. Please check Operator logs
  Warning  UpdateFailed   4m3s (x16 over 4m27s)   CSIScaleOperator  Synchronization of node/driver ibm-spectrum-scale-csi DaemonSet failed for the CSISCaleOperator instance ibm-spectrum-scale-csi
  Warning  UpdateFailed   65s                     CSIScaleOperator  Failed to set defaults on the instance ibm-spectrum-scale-csi. Please check Operator logs
  Warning  UpdateFailed   54s (x14 over 67s)      CSIScaleOperator  Synchronization of node/driver ibm-spectrum-scale-csi DaemonSet failed for the CSISCaleOperator instance ibm-spectrum-scale-csi
```
Images :
```
[root@saurabh6-master pr1002]# oc describe pod | grep quay
    Image:         quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
    Image ID:      quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
  Normal   Pulled     8m10s              kubelet            Container image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7" already present on machine
    Image:         quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:events_gui_pass_v9
    Image ID:      quay.io/badri_pathak/ibm-spectrum-scale-csi-operator@sha256:a31ef1636903b3f3f75406cc463d0045a5064c7db12d59b07a322e89259e2065
      CSI_DRIVER_IMAGE:      quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:ee9bd3e431cf0d3fb1e407a6e2ed51d6be957dd1445c2cd88f329cbb5b1ea494
  Normal  Pulled     4m20s  kubelet            Container image "quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:events_gui_pass_v9" already present on machine
    Image:         quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
    Image ID:      quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7
  Normal   Pulled     8m10s              kubelet            Container image "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver@sha256:573b3b2d349359d7871d53060a0fc7df6e03de2e2900d1be46b4146ab1972fb7" already present on machine
```

**Comment by amdabhad** [comment]
@badri-pathak, please check this

**Comment by badri-pathak** [comment]
@saurabhwani5 Can you please share the configMap data which is already present or being created to regenerate this issue?

**Comment by saurabhwani5** [comment]
Used the same as mentioned above

**Comment by badri-pathak** [comment]
@saurabhwani5  Please find the image for the validation quay.io/badri_pathak/ibm-spectrum-scale-csi-operator:cmfix_v3

**Comment by saurabhwani5** [comment]
verified with above Image. Thank You @badri-pathak
